export enum ReportErrorCode {
  // TODO: e.g. REPORT_001 = 'REPORT_001',
  REPORT_INVALID_DATE_FORMAT = 'REPORT_INVALID_DATE_FORMAT',
  WEEKLY_REPORT_FETCH_FAILED = 'WEEKLY_REPORT_FETCH_FAILED',

  REPORT_INVALID_MONTH_FORMAT = 'REPORT_INVALID_MONTH_FORMAT',
  MONTHLY_REPORT_FETCH_FAILED = 'MONTHLY_REPORT_FETCH_FAILED',

  REPORT_INVALID_DATE_RANGE = 'REPORT_INVALID_DATE_RANGE',
  REPORT_PDF_RANGE_EXCEEDED = 'REPORT_PDF_RANGE_EXCEEDED',
  REPORT_DATA_NOT_FOUND = 'REPORT_DATA_NOT_FOUND',
  REPORT_PDF_GENERATION_FAILED = 'REPORT_PDF_GENERATION_FAILED',
}
