export enum UserErrorCode {
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_WITHDRAWN = 'USER_WITHDRAWN',
  NICKNAME_REQUIRED = 'NICKNAME_REQUIRED',
  NICKNAME_TOO_LONG = 'NICKNAME_TOO_LONG',
  INVALID_GENDER = 'INVALID_GENDER',
  INVALID_AGE_GROUP = 'INVALID_AGE_GROUP',
  INVALID_BASELINE_TYPE = 'INVALID_BASELINE_TYPE',
  ONBOARDING_ALREADY_COMPLETED = 'ONBOARDING_ALREADY_COMPLETED',
}
