export enum GuideErrorCode {
  // TODO: e.g. GUIDE_001 = 'GUIDE_001',
  GUIDE_INVALID_ID = 'GUIDE_INVALID_ID',

  GUIDE_INVALID_WEEK_FORMAT = 'GUIDE_INVALID_WEEK_FORMAT',
  GUIDE_INVALID_MONTH_FORMAT = 'GUIDE_INVALID_MONTH_FORMAT',
  GUIDE_INVALID_FEEDBACK = 'GUIDE_INVALID_FEEDBACK',

  GUIDE_CONTENT_NOT_FOUND = 'GUIDE_CONTENT_NOT_FOUND',
  GUIDE_CONTENT_INACTIVE = 'GUIDE_CONTENT_INACTIVE',
  GUIDE_RULE_NOT_FOUND = 'GUIDE_RULE_NOT_FOUND',

  GUIDE_FEEDBACK_ALREADY_EXISTS = 'GUIDE_FEEDBACK_ALREADY_EXISTS',
  GUIDE_FEEDBACK_NOT_FOUND = 'GUIDE_FEEDBACK_NOT_FOUND',

  GUIDE_FETCH_FAILED = 'GUIDE_FETCH_FAILED',
  GUIDE_DETAIL_FETCH_FAILED = 'GUIDE_DETAIL_FETCH_FAILED',
  GUIDE_FEEDBACK_CREATE_FAILED = 'GUIDE_FEEDBACK_CREATE_FAILED',
  GUIDE_FEEDBACK_UPDATE_FAILED = 'GUIDE_FEEDBACK_UPDATE_FAILED',
  GUIDE_FEEDBACK_DELETE_FAILED = 'GUIDE_FEEDBACK_DELETE_FAILED',
}
